// Add product to cart in localStorage
function addToCart(productName) {
	const product = products.find(p => p.name === productName);
	if (!product) return alert('Product not found!');
	let cart = JSON.parse(localStorage.getItem('cart')) || [];
	cart.push(product);
	localStorage.setItem('cart', JSON.stringify(cart));
	alert(`${product.name} added to cart!`);
}
// Product data for the app
const products = [
	{id: 1, name: "Wireless Earbuds", price: 1999, image: "assets/product/earbuds.jpg", description: "High quality sound, long battery life, GenZ style."},
	{id: 2, name: "Smart Watch", price: 3499, image: "assets/product/smartwatch.jpg", description: "Track your fitness and notifications in style."},
	{id: 3, name: "Bluetooth Speaker", price: 1499, image: "assets/product/speaker.jpg", description: "Portable, powerful, and perfect for parties."},
	{id: 4, name: "Gaming Mouse", price: 1299, image: "assets/product/mouse.jpg", description: "Precision and speed for every gamer."},
	{id: 5, name: "LED Ring Light", price: 899, image: "assets/product/ringlight.jpg", description: "Perfect lighting for selfies and streams."},
	{id: 6, name: "Portable Charger", price: 799, image: "assets/product/charger.jpg", description: "Charge your devices on the go."},
	{id: 7, name: "Fitness Tracker", price: 1599, image: "assets/product/fitnesstracker.jpg", description: "Monitor your health and activity."},
	{id: 8, name: "VR Headset", price: 4999, image: "assets/product/vr.jpg", description: "Step into virtual worlds."},
	{id: 9, name: "Noise Cancelling Headphones", price: 2999, image: "assets/product/headphones.jpg", description: "Block out the world, enjoy your music."},
	{id: 10, name: "Smartphone Gimbal", price: 2499, image: "assets/product/gimbal.jpg", description: "Smooth video for creators."},
	{id: 11, name: "Action Camera", price: 3999, image: "assets/product/actioncam.jpg", description: "Capture your adventures."},
	{id: 12, name: "Mini Projector", price: 3499, image: "assets/product/projector.jpg", description: "Big screen anywhere."},
	{id: 13, name: "Wireless Keyboard", price: 999, image: "assets/product/keyboard.jpg", description: "Type with comfort and style."},
	{id: 14, name: "Smart Bulb", price: 499, image: "assets/product/bulb.jpg", description: "Control your lighting from your phone."},
	{id: 15, name: "USB Hub", price: 399, image: "assets/product/usbhub.jpg", description: "Expand your connectivity."},
	{id: 16, name: "Laptop Stand", price: 699, image: "assets/product/laptopstand.jpg", description: "Ergonomic and portable."},
	{id: 17, name: "Webcam", price: 1299, image: "assets/product/webcam.jpg", description: "Crystal clear video calls."},
	{id: 18, name: "Smart Plug", price: 599, image: "assets/product/smartplug.jpg", description: "Automate your home."},
	{id: 19, name: "Wireless Mouse", price: 799, image: "assets/product/wirelessmouse.jpg", description: "No wires, no hassle."},
	{id: 20, name: "Tablet", price: 6999, image: "assets/product/tablet.jpg", description: "Portable productivity."},
	{id: 21, name: "E-Book Reader", price: 4999, image: "assets/product/ereader.jpg", description: "Read anywhere, anytime."},
	{id: 22, name: "Smart Thermostat", price: 2999, image: "assets/product/thermostat.jpg", description: "Control your climate."},
	{id: 23, name: "Robot Vacuum", price: 7999, image: "assets/product/vacuum.jpg", description: "Effortless cleaning."},
	{id: 24, name: "Electric Toothbrush", price: 999, image: "assets/product/toothbrush.jpg", description: "Advanced dental care."},
	{id: 25, name: "Smart Scale", price: 1499, image: "assets/product/scale.jpg", description: "Track your weight and health."},
	{id: 26, name: "Dash Cam", price: 2499, image: "assets/product/dashcam.jpg", description: "Record your drives."},
	{id: 27, name: "Portable SSD", price: 3499, image: "assets/product/ssd.jpg", description: "Fast, reliable storage."},
	{id: 28, name: "Wireless Router", price: 1999, image: "assets/product/router.jpg", description: "High-speed internet."},
	{id: 29, name: "Smart Lock", price: 3999, image: "assets/product/smartlock.jpg", description: "Secure your home smartly."},
	{id: 30, name: "Streaming Stick", price: 2499, image: "assets/product/streaming.jpg", description: "TV, movies, and more."},
	{id: 31, name: "Photo Printer", price: 2999, image: "assets/product/printer.jpg", description: "Print memories instantly."},
	{id: 32, name: "Wireless Charger", price: 899, image: "assets/product/wirelesscharger.jpg", description: "Charge with ease."},
	{id: 33, name: "Smart Mirror", price: 5999, image: "assets/product/mirror.jpg", description: "Tech meets beauty."},
	{id: 34, name: "Fitness Smart Scale", price: 1799, image: "assets/product/fitnessextreme.jpg", description: "Track more than just weight."},
	{id: 35, name: "Smart Water Bottle", price: 799, image: "assets/product/waterbottle.jpg", description: "Stay hydrated smartly."},
	{id: 36, name: "Bluetooth Tracker", price: 499, image: "assets/product/tracker.jpg", description: "Never lose your stuff."},
	{id: 37, name: "Smart Fan", price: 2499, image: "assets/product/fan.jpg", description: "Cool and connected."},
	{id: 38, name: "Electric Kettle", price: 1299, image: "assets/product/kettle.jpg", description: "Boil water fast."},
	{id: 39, name: "Smart TV", price: 15999, image: "assets/product/tv.jpg", description: "Entertainment redefined."},
	{id: 40, name: "Gaming Chair", price: 5999, image: "assets/product/chair.jpg", description: "Comfort for long sessions."},
	{id: 41, name: "Smart Fridge", price: 29999, image: "assets/product/fridge.jpg", description: "Keep food fresh, stay connected."},
	{id: 42, name: "Air Purifier", price: 4999, image: "assets/product/airpurifier.jpg", description: "Breathe easy."},
	{id: 43, name: "Smart Oven", price: 8999, image: "assets/product/oven.jpg", description: "Cook with precision."},
	{id: 44, name: "Electric Scooter", price: 24999, image: "assets/product/scooter.jpg", description: "Commute in style."},
	{id: 45, name: "Smart Doorbell", price: 2999, image: "assets/product/doorbell.jpg", description: "See who's there."},
	{id: 46, name: "Smart Air Conditioner", price: 24999, image: "assets/product/ac.jpg", description: "Cool your home smartly."},
	{id: 47, name: "Smart Washing Machine", price: 19999, image: "assets/product/washingmachine.jpg", description: "Laundry made easy."},
	{id: 48, name: "Smart Coffee Maker", price: 4999, image: "assets/product/coffeemaker.jpg", description: "Perfect coffee every time."},
	{id: 49, name: "Smart Blender", price: 2999, image: "assets/product/blender.jpg", description: "Blend with intelligence."},
	{id: 50, name: "Smart Rice Cooker", price: 3999, image: "assets/product/ricecooker.jpg", description: "Fluffy rice, every time."},
	// ... 50 more products for a total of 100 ...
	{id: 51, name: "Smart Toothbrush", price: 1299, image: "assets/product/toothbrush2.jpg", description: "Track your brushing habits."},
	{id: 52, name: "Smart Mug", price: 999, image: "assets/product/mug.jpg", description: "Keep your drink at the perfect temp."},
	{id: 53, name: "Smart Backpack", price: 2499, image: "assets/product/backpack.jpg", description: "Charge devices on the go."},
	{id: 54, name: "Smart Alarm Clock", price: 1499, image: "assets/product/alarmclock.jpg", description: "Wake up smarter."},
	{id: 55, name: "Smart Pet Feeder", price: 2999, image: "assets/product/petfeeder.jpg", description: "Feed your pet remotely."},
	{id: 56, name: "Smart Jump Rope", price: 799, image: "assets/product/jumprope.jpg", description: "Track your workout."},
	{id: 57, name: "Smart Skipping Rope", price: 899, image: "assets/product/skippingrope.jpg", description: "Count your skips."},
	{id: 58, name: "Smart Yoga Mat", price: 1999, image: "assets/product/yogamat.jpg", description: "Track your poses."},
	{id: 59, name: "Smart Water Purifier", price: 4999, image: "assets/product/waterpurifier.jpg", description: "Clean water, always."},
	{id: 60, name: "Smart Luggage", price: 5999, image: "assets/product/luggage.jpg", description: "Track your bags."},
	{id: 61, name: "Smart Plant Pot", price: 999, image: "assets/product/plantpot.jpg", description: "Monitor your plants."},
	{id: 62, name: "Smart Desk Lamp", price: 799, image: "assets/product/lampsmart.jpg", description: "Light up your workspace."},
	{id: 63, name: "Smart Pen", price: 499, image: "assets/product/pen.jpg", description: "Digitize your notes."},
	{id: 64, name: "Smart Wallet", price: 1499, image: "assets/product/wallet.jpg", description: "Track your wallet."},
	{id: 65, name: "Smart Key Finder", price: 599, image: "assets/product/keyfinder.jpg", description: "Never lose your keys."},
	{id: 66, name: "Smart Door Sensor", price: 799, image: "assets/product/doorsensor.jpg", description: "Know when doors open."},
	{id: 67, name: "Smart Window Sensor", price: 799, image: "assets/product/windowsensor.jpg", description: "Monitor your windows."},
	{id: 68, name: "Smart Garage Opener", price: 2999, image: "assets/product/garageopener.jpg", description: "Open your garage remotely."},
	{id: 69, name: "Smart Sprinkler", price: 3999, image: "assets/product/sprinkler.jpg", description: "Water your lawn smartly."},
	{id: 70, name: "Smart Egg Tray", price: 499, image: "assets/product/eggtray.jpg", description: "Track your eggs."},
	{id: 71, name: "Smart Trash Can", price: 1999, image: "assets/product/trashcan.jpg", description: "Hands-free trash."},
	{id: 72, name: "Smart Shower", price: 9999, image: "assets/product/shower.jpg", description: "Perfect temperature every time."},
	{id: 73, name: "Smart Hair Dryer", price: 2999, image: "assets/product/hairdryer.jpg", description: "Dry your hair smartly."},
	{id: 74, name: "Smart Iron", price: 1999, image: "assets/product/iron.jpg", description: "Wrinkle-free clothes."},
	{id: 75, name: "Smart Fan Heater", price: 2499, image: "assets/product/fanheater.jpg", description: "Warm up quickly."},
	{id: 76, name: "Smart Air Cooler", price: 4999, image: "assets/product/aircooler.jpg", description: "Stay cool all summer."},
	{id: 77, name: "Smart Humidifier", price: 2999, image: "assets/product/humidifier.jpg", description: "Perfect humidity."},
	{id: 78, name: "Smart Dehumidifier", price: 2999, image: "assets/product/dehumidifier.jpg", description: "Remove excess moisture."},
	{id: 79, name: "Smart Candle", price: 399, image: "assets/product/candle.jpg", description: "Set the mood smartly."},
	{id: 80, name: "Smart Night Light", price: 499, image: "assets/product/nightlight.jpg", description: "Gentle light for sleep."},
	{id: 81, name: "Smart Thermos", price: 999, image: "assets/product/thermos.jpg", description: "Keep drinks hot or cold."},
	{id: 82, name: "Smart Pillow", price: 1999, image: "assets/product/pillow.jpg", description: "Sleep smarter."},
	{id: 83, name: "Smart Mattress", price: 14999, image: "assets/product/mattress.jpg", description: "Track your sleep."},
	{id: 84, name: "Smart Blanket", price: 2999, image: "assets/product/blanket.jpg", description: "Stay warm smartly."},
	{id: 85, name: "Smart Socks", price: 499, image: "assets/product/socks.jpg", description: "Track your steps."},
	{id: 86, name: "Smart Shoes", price: 2999, image: "assets/product/shoes.jpg", description: "Track your runs."},
	{id: 87, name: "Smart T-shirt", price: 999, image: "assets/product/tshirt.jpg", description: "Monitor your activity."},
	{id: 88, name: "Smart Jacket", price: 3999, image: "assets/product/jacket.jpg", description: "Stay warm and connected."},
	{id: 89, name: "Smart Hat", price: 799, image: "assets/product/hat.jpg", description: "Track your sun exposure."},
	{id: 90, name: "Smart Glasses", price: 4999, image: "assets/product/glasses.jpg", description: "Augmented reality eyewear."},
	{id: 91, name: "Smart Watch Band", price: 499, image: "assets/product/watchband.jpg", description: "Style and function."},
	{id: 92, name: "Smart Ring", price: 1999, image: "assets/product/ring.jpg", description: "Track your health."},
	{id: 93, name: "Smart Bracelet", price: 999, image: "assets/product/bracelet.jpg", description: "Monitor your wellness."},
	{id: 94, name: "Smart Necklace", price: 1499, image: "assets/product/necklace.jpg", description: "Fashion meets tech."},
	{id: 95, name: "Smart Earrings", price: 799, image: "assets/product/earrings.jpg", description: "Style and sound."},
	{id: 96, name: "Smart Belt", price: 999, image: "assets/product/belt.jpg", description: "Track your waistline."},
	{id: 97, name: "Smart Wallet Chain", price: 499, image: "assets/product/walletchain.jpg", description: "Keep your wallet secure."},
	{id: 98, name: "Smart Tie", price: 799, image: "assets/product/tie.jpg", description: "Track your meetings."},
	{id: 99, name: "Smart Scarf", price: 999, image: "assets/product/scarf.jpg", description: "Stay warm and stylish."},
	{id: 100, name: "Smart Watch Charger", price: 599, image: "assets/product/watchcharger.jpg", description: "Charge your watch fast."}
];

// Export products for use in other scripts
if (typeof module !== 'undefined') {
	module.exports = products;
}
